apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ub76zwflv-go 
  janus-idp.io/tekton: ub76zwflv-go
  backstage.io/kubernetes-id: ub76zwflv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ub76zwflv-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  