apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ub76zwflv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ub76zwflv-go 
  name: ub76zwflv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ub76zwflv-go 
